name: Run Playwright Tests

on:
  schedule:
    - cron: '0 8 * * 1-5'  # Runs at 8:00 AM every Monday to Friday
  workflow_dispatch:

jobs:
  playwright-test:
    runs-on: ubuntu-latest

    env:
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # You can use a different Node.js version

    - name: Install dependencies
      run: |
        npm ci

    - name: Run Playwright tests

      run: |
        npx playwright install
        npx playwright test in.spec.js